version: '3.5'
services:

  akaunting:
    image: akaunting:latest
    ports:
      - 8002:80
      - 8003:443
    restart: always
    volumes:
      - akauntingdata:/var/www/html/akaunting
      - akauntingapache:/etc/apache2/sites-available
      - akauntingle:/etc/letsencrypt
      - akauntinglelib:/var/lib/letsencrypt
  db:
    image: mysql:latest 
    ports:
      - 3306:3306
    restart: always
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd

volumes:
    akauntingdata:
    akauntingapache:
    akauntingle:
    akauntinglelib:
    db:

